services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CinemaCluster
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CinemaCluster
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M
    depends_on:
      cassandra1:
        condition: service_started
